# Generated by Django 2.0.2 on 2018-04-05 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180405_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='message',
        ),
        migrations.AddField(
            model_name='blog',
            name='body',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
